fn main() {
	println!("Hello world");
}



/*UN MACRO ES COMO UN GENERICO EN JAVA*/
/*
	*MULTIPARADIGMA
	*TIPADO ESTAICO
	*CONCURRENTE -> LAS VARIABLES SON INMUTABLES POR DEFECTO
				X= 5 ; TODA SU VIDA 5 AL MENOS Q LA MARQUE COMO MUTABLE

	*MANEJO DE MEMORIA INTERESANTE  -> EN C++ ACEDO A UN PUNTERO DESCONOCIDO Y NO ME DEJA
									EN RUST NO ME PERMITE ACER CODIGO Q SE CUELGE NO COMPILA


	SOLO HILO PROGRAMACION ASINCRONA

*/

